### ISSUE TITLE
Send email for RSVP not working

### ISSUE THREAD

**Issue by arox86** [jdleesmiller/wedding#26]
Hello, I use I have problems with sending emails when a guest has signed up. I started the app with the docker-compose up -d command. It runs on an Ubuntu server 21.04 LTS. I have opened the ports 3000, 5432 and 465 in the internal firewall ufw and my router for the server. I can access the site externally and operate everything. only the email dispatch for RSVP does not work. I use gmail as SMTP server.
my development.env looks like this:

CANONICAL_HOST=www.myname.com
CONTACT_EMAIL=myname@gmail.com
FROM_EMAIL=myname@gmail.com
SMTP_ADDRESS=smtp.gmail.com
SMTP_PORT=465
SMTP_DOMAIN=gmail.com
SMTP_USER_NAME=myname@gmail.com
SMTP_PASSWORD=password
SMTP_AUTHENTICATION=login
SMTP_ENABLE_STARTTLS_AUTO=true
SEND_EMAIL_IN_DEVELOPMENT=true

the output from the log says:
 GuestMailer#welcome_back_email: processed outbound mail in 532.8ms
web_1  | Sent mail to myname@web.de (23.5ms)

**Comment by rnestler** [comment]
I also had issues with sending emails via fastmail and got errors like `SMTPSyntaxError (501 5.5.4 Invalid argument` in the logs.

I could solve it by removing the `domain: ENV['SMTP_DOMAIN']` line from `config/environments/production.rb`. See also https://stackoverflow.com/questions/18579439/actionmailer-responds-with-501-5-5-4-invalid-argument.

**Comment by arox86** [comment]
thx a lot!
